version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile-app
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./app:/winamaxTest/app
    env_file:
      - app/env/.env
    depends_on:
      - redis
    command: npm run dev
  worker:
    build: 
      context: .
      dockerfile: ./dockerfile-worker
    env_file:
      - ./worker/env/.env
    volumes:
      - ./worker:/winamaxTest/worker
    depends_on:
      - app
    command: npm run dev
    deploy:
      mode: replicated
      replicas: ${instances:-5}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"