version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/winamaxTest/app
    env_file:
      - app/env/.env
    depends_on:
      - redis
    command: npm run dev
  worker:
    build: 
      context: .
      dockerfile: ./dockerfile-worker
    volumes:
      - ./worker:/winamaxTest/app
    env_file:
      - ./worker/env/.env
    depends_on:
      - redis
      - app
  redis:
    image: redis:latest
    ports:
      - "6379:6379"