version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    env_file:
      - app/env/.env
    depends_on:
      - redis
    command: npm run dev
  redis:
    image: redis:latest
    ports:
      - "6379:6379"